### ISSUE TITLE
Feature Request - Dynamic SMO for SP Library Interaction

### ISSUE THREAD

**Issue by sarapaispires** [K2NE/K2NESPContentBroker#10]
Hello,

We are currently using the the K2NESPContentBroker to access libraries within subsites in SPO, but have encountered a potential escalation problem. The broker as is only allows for individual SmartObjects to be created for each library contained in a subsite. This means that for each new library, identical to an existing one, a new SmartObject, also identical to the previous one, has to be created. 
Given that a lot of developing work has to be repeated, as the project grows, and more SmartObjects, all identical to one another, have to be created, we would like to ask if it would be possible to create a SmartObject that would work one layer above and allow for the selection of the library with which we want to interact and the respective subsite.

Thank you for your time and all the effort put into this project!

Regards

**Comment by sarapaispires** [comment]
Hi,

Indeed, it has. However, it would be equally great to be able to choose within the same subsite in a site collection the library to which you want to access, instead of having to use a different SmartObject for each. Would it be a viable option?

Thank you!

**Comment by cyclops1982** [comment]
@sarapaispires - i don't think i fully understand what you would need. Do you mean you would want to provide the library name as a parameter to the smartobject as well?
This would work with a list/library that has the same properties, but would fail when it does not have the same properties.

**Comment by sarapaispires** [comment]
@cyclops1982, I apologize for the late response.

That would be exactly what we would need, to pass the library/list name as a parameter. In our case, the libraries have the same properties, and that is why it would be great to have simply one SmartObject that could, for example, upload a document to the correct library, according to business rules and information coming from a SmartForm.

Thank you!

**Comment by cyclops1982** [comment]
Hi Sara,

Will have to see how big the impact of this would be on the code, i think it could work - but we worry about making the code too complex for this.

**Comment by cyclops1982** [comment]
I had a quick look at what the impact would be for this:
- The service broker currently uses methods to add the service object methods. These methods have a section of code at the top like this:
``
     if (base.IsDynamicSiteURL)
            {
                Helper.AddSiteURLParameter(mGetItemById);
            }
``
The above code adds the SiteURL parameter. I think we can do something similar for LibraryName and refactor the code a bit to move this to one central place where we add SiteURL parameter and LibraryName parameter.

- Every execute method needs to be updated to check if the library name was supplied and if so, use that name. The impact of that might be different on every bit of code.  In most cases, we do a ServiceObject.GetListTitle to get the list title, if we could update that method to check if listname was provided, then the impact of the code is fairly low, but will still require testing on all methods.

**Comment by panjkov** [comment]
The challenge for this approach would be that we need to have  "Catch All" logic for Document Library properties. So, it is virtually impossible to have completely generic SmartObject, as we would need to point to some Document Library when we create SmartObject. We could, though, use default Document Library as template when we create the SMO, but that would not take any of custom fields into account.

**Comment by sarapaispires** [comment]
Hello,

We have created a Document Library at the site collection level and generated a template from it. This template is then used to generate all the Document Libraries at the subsite level, and are, therefore, all equal between one another. Could this template be used to generate the SMO?

**Comment by panjkov** [comment]
@sarapaispires that would certainly add complexity and take long to implement.
@cyclops1982 I was thinking about adding two additional configuration properties to the Service Broker / Service Instance where we could add Library Name and List Name for "Source" doc lib and then generate additional Dynamic Service Object in the Service Instance. Then, we could perhaps do the following logic:
1. If "dynamic" and "doclib/listname not empty" use that doclib as a source for Dynamic Library Service Object
2. If "dynamic" and "doclib/listname is empty" don't create dynamic Library Service Object, only create service objects for doclibs and lists (with dynaic site URL)
3. If "not dynamic" then don't create any dynamicobjects (only objects for current site)

**Comment by cyclops1982** [comment]
Hmm, my thinking around this was a lot simpler :)
I would just add a parameter to the methods based on a service intance configration option. That parameter is for the library name and if it's supplied, then we try to use that library name instead of the default one.

This has the result that you can create one site with a (or more) libraries that are your template libraries. Then you can use the URL and library name parameter ot address other lists that look exactly the same.

It's flexible and i believe covers all scenario's that we currently have.

**Comment by panjkov** [comment]
@cyclops1982 good point there.

**Comment by panjkov** [comment]
Resolved in #26 and #27
