### ISSUE TITLE
Solution is not SP2013 and SP2016 compatible?

### ISSUE THREAD

**Issue by cyclops1982** [K2NE/K2NESPContentBroker#18]
There are some assemblies supplied that are Version 15, but we also have seen Version 16 assemblies.
Furthermore, it seems that the taxonomy namespace is different between these two versions.

Then, it seems that SP Online also has a specific version of CSOM SDK available. 

The solution would (ideally) work on SP2013 (v15), SP2016 (v16) and SP online (v16.something).
I think this would require some build flags to select which SP version you would want to build, but i'm not sure if that's enough and if it's even possible to do so.

Marking this as a bug and feature request, as the desired aim of the broker is to support both SP2013, SP2016 and SPO.

**Comment by panjkov** [comment]
We can do something like this:

https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
